[package]
name = "strategies"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
log = "0.4.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
splines = "4.2"
nalgebra = "0.32"

