[package]
name = "binance-exchange"
version = "0.1.0"
edition = "2024"

[dependencies]
binance_spot_connector_rust = { git = "https://github.com/binance/binance-spot-connector-rust.git", version = "1.3.0", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
log = "0.4"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1"
