# Adaptive Multi-Factor Strategy Configuration
# Optimized for profitability using momentum-based approach

# Core parameters
short_window = 8
long_window = 30
volatility_window = 15
volume_window = 20
volatility_multiplier = 1.5
momentum_threshold = 0.01
volume_threshold = 1.2

# Signal filtering - Made more aggressive for trade generation
signal_threshold = 0.01

# Risk Management
max_position_size = 0.1  # Maximum 10% of portfolio per trade
stop_loss_pct = 0.02     # 2% stop loss
take_profit_pct = 0.04   # 4% take profit

# Market Regime Adjustments
[low_volatility]
momentum_threshold = 0.015
volatility_multiplier = 1.5

[high_volatility]
momentum_threshold = 0.025
volatility_multiplier = 2.5

[extreme_volatility]
momentum_threshold = 0.03
volatility_multiplier = 3.0 