# Advanced Multi-Timeframe Momentum Strategy Configuration
# Addresses key issues: low trade frequency, poor win rate, high drawdown, fee erosion

# Multi-timeframe parameters
short_period = 2              # Ultra-short for immediate signals
medium_period = 5             # Medium for trend confirmation
long_period = 15              # Long for overall direction

# Volume analysis
volume_period = 10            # Volume analysis window
volume_threshold = 1.0        # Lower volume spike threshold

# Momentum parameters
momentum_period = 3           # Momentum calculation period
momentum_threshold = 0.00001  # Very low threshold for more signals

# Trend analysis
trend_period = 10             # Trend calculation period
trend_threshold = 0.0001      # Lower trend strength threshold

# Adaptive parameters
volatility_period = 10        # Volatility calculation period
adaptive_threshold = 0.1      # Lower base adaptive threshold

# Risk management
max_position_size = 1000.0    # Maximum position size
stop_loss_pct = 0.02          # 2% stop loss
take_profit_pct = 0.04        # 4% take profit

# Signal filtering
signal_threshold = 0.1        # Lower base signal threshold
min_volume_ratio = 0.5        # Lower minimum volume ratio for signals 