[general]
strategy_name = "CorrelationDiversifiedPortfolioStrategy"
max_assets = 10
target_correlation_threshold = 0.3

[correlation]
lookback_period = 50
correlation_window = 20
min_correlation = 0.0
max_correlation = 0.8
correlation_decay_factor = 0.3

[rebalancing]
rebalance_frequency_ms = 1000    # 1 second
min_weight_change = 0.001        # 0.1% minimum weight change to trigger rebalancing
max_weight_change = 0.20         # 20% maximum weight change per rebalancing
target_volatility = 0.15         # 15% target portfolio volatility
volatility_scaling = true

[risk]
max_portfolio_weight = 0.30      # Maximum 30% in any single asset
min_portfolio_weight = 0.05      # Minimum 5% in any single asset
max_drawdown = 0.10              # 10% maximum drawdown
stop_loss_threshold = 0.05       # 5% stop loss threshold
position_sizing_factor = 0.25    # Conservative position sizing
