[general]
strategy_name = "EnhancedPulsarStrategy"
base_size = 20.0
max_position = 100.0

[regime_detection]
# Market regime detection parameters
volatility_window = 50
trend_window = 30
momentum_window = 20
regime_confidence_threshold = 0.7
volatility_threshold_high = 0.002
volatility_threshold_low = 0.0005
trend_strength_threshold = 0.6

[signals]
# Signal generation parameters
min_confidence = 0.6
momentum_threshold = 0.001
mean_reversion_threshold = 0.002
breakout_threshold = 0.003
volume_threshold = 1.5

[signals.regime_weights]
# Confidence weights for different market regimes
trending_weight = 1.2
mean_reverting_weight = 1.0
volatile_weight = 0.8
sideways_weight = 0.9
breakout_weight = 1.3

[risk_management]
# Risk management parameters
max_drawdown = 0.05
max_consecutive_losses = 3
dynamic_stop_loss = true
trailing_stop = true

[risk_management.regime_risk_multipliers]
# Risk multipliers for different market regimes
trending_multiplier = 1.0
mean_reverting_multiplier = 0.8
volatile_multiplier = 0.6
sideways_multiplier = 0.9
breakout_multiplier = 1.1

[position_sizing]
# Position sizing parameters
base_size = 20.0
confidence_multiplier = 1.0
volatility_adjustment = true

[position_sizing.regime_size_multipliers]
# Position size multipliers for different market regimes
trending_multiplier = 1.2
mean_reverting_multiplier = 0.9
volatile_multiplier = 0.7
sideways_multiplier = 0.8
breakout_multiplier = 1.1
