# Fractal Approximation Strategy Configuration
# Optimized for profitability using momentum-based approach

# Core parameters
period = 20
scale = 2.0

# Signal filtering - Made more aggressive for trade generation
signal_threshold = 0.01
momentum_threshold = 0.00001 