# Fractal Approximation Strategy Configuration
# Optimized for profitability using momentum-based approach

# Core parameters
period = 20
scale = 2.0

# Signal filtering
signal_threshold = 0.1
momentum_threshold = 0.00005 