# Game Theory + Adversarial ML Strategy Configuration

# Game Theory Parameters
game_theory_enabled = true
nash_confidence_threshold = 0.5
minmax_threshold = 0.4
equilibrium_calculation_frequency = 10
player_model_update_rate = 0.1

# Adversarial ML Parameters
adversarial_ml_enabled = true
adversarial_threat_threshold = 0.7
attack_detection_sensitivity = 0.5
defense_mechanism_effectiveness = 0.8
counter_attack_threshold = 0.8

# Market Regime Detection
regime_detection_window = 20
trend_strength_threshold = 0.7
mean_reversion_threshold = 0.6
volatility_threshold = 0.003
manipulation_detection_sensitivity = 0.8

# Attack Pattern Detection
front_running_detection_threshold = 0.6
spoofing_detection_threshold = 0.7
momentum_manipulation_threshold = 0.5
liquidity_removal_threshold = 0.6

# Risk Management
max_position_size = 1000.0
stop_loss_threshold = 0.005
take_profit_threshold = 0.008
max_consecutive_losses = 3
min_win_rate_threshold = 0.55

# Nash Equilibrium Parameters
nash_calculation_method = "regime_based"
equilibrium_adaptation_rate = 0.1
minmax_strategy_weight = 0.5
nash_strategy_weight = 0.5

# Adversarial Defense Parameters
defense_mode = "adaptive"
evasion_threshold = 0.7
cooperation_threshold = 0.3
deflection_threshold = 0.6

# Performance Tracking
track_nash_equilibrium_accuracy = true
track_minmax_strategy_performance = true
track_adversarial_detection_rate = true
track_defense_effectiveness = true
adaptive_parameters = true

# Signal Generation
min_confidence_for_trade = 0.6
signal_decay_rate = 0.9
ensemble_voting = true
model_uncertainty = true

# Position Management
position_sizing_factor = 0.1
max_positions_per_side = 1
position_rotation_enabled = true
quick_exit_threshold = 0.002

# Advanced Features
use_nash_equilibrium = true
use_minmax_strategy = true
use_adversarial_detection = true
use_defense_mechanisms = true
use_regime_adaptation = true

# Model Training
online_learning = true
retrain_frequency = 500
feature_selection = true
cross_validation = false
early_stopping = true

# Performance Optimization
prediction_cache_size = 50
feature_cache_size = 25
model_update_frequency = 5
memory_efficient = true

# Game Theory Components
use_payoff_matrix = false
use_player_modeling = true
use_equilibrium_calculation = true
use_strategy_adaptation = true

# Adversarial Components
use_attack_detection = true
use_counter_attacks = false
use_evasion_strategies = true
