# HFT Ultra-Fast Strategy Configuration
# Best for: Ultra-low latency directional trading, momentum capture

# Core Parameters (optimized for speed)
buffer_size = 64              # Fixed buffer size for minimal allocations
fast_ema_alpha = 0.1          # Fast EMA smoothing (10-period equivalent)
slow_ema_alpha = 0.05         # Slow EMA smoothing (20-period equivalent)
volatility_window = 10        # Short volatility calculation window

# Signal Thresholds (microsecond-level)
buy_threshold = 0.0005        # 0.05% price change threshold
sell_threshold = -0.0005      # -0.05% price change threshold
volume_threshold = 1.2        # 20% above average volume
signal_threshold = 0.6        # 60% confidence threshold

# Risk Management (tight for HFT)
stop_loss_pct = 0.002         # 0.2% stop loss
take_profit_pct = 0.002       # 0.2% take profit
max_position_size = 0.05      # 5% max position size

# Performance Optimization
enable_inline = true          # Enable inline functions
use_fixed_arrays = true       # Use fixed arrays instead of VecDeque
minimal_branching = true      # Minimize conditional branching 