# HFT Trading Strategies Configuration
# Optimized for ultra-low latency and high-frequency trading

[hft_ultra_fast]
# HFT Ultra-Fast Strategy Configuration
# Best for: Ultra-low latency directional trading, momentum capture

# Core Parameters (optimized for speed)
buffer_size = 64              # Fixed buffer size for minimal allocations
fast_ema_alpha = 0.1          # Fast EMA smoothing (10-period equivalent)
slow_ema_alpha = 0.05         # Slow EMA smoothing (20-period equivalent)
volatility_window = 10        # Short volatility calculation window

# Signal Thresholds (microsecond-level)
buy_threshold = 0.0005        # 0.05% price change threshold
sell_threshold = -0.0005      # -0.05% price change threshold
volume_threshold = 1.2        # 20% above average volume

# Risk Management (tight for HFT)
stop_loss_pct = 0.002         # 0.2% stop loss
take_profit_pct = 0.002       # 0.2% take profit
max_position_size = 0.05      # 5% max position size

# Performance Optimization
enable_inline = true          # Enable inline functions
use_fixed_arrays = true       # Use fixed arrays instead of VecDeque
minimal_branching = true      # Minimize conditional branching

[hft_market_maker]
# HFT Market Maker Strategy Configuration
# Best for: Spread capture, order book analysis, inventory management

# Order Book Parameters
spread_multiplier = 1.5       # Multiplier for optimal spread calculation
min_spread = 0.0001           # 0.01% minimum spread
max_position = 1000.0         # Maximum position size
inventory_target = 0.0        # Target inventory (0 = neutral)

# Inventory Management
max_inventory = 5000.0        # Maximum inventory before hedging
hedge_threshold = 0.8         # Hedge when inventory > 80% of max
inventory_cost_weight = 0.1   # Weight for inventory cost in P&L

# Risk Controls
max_loss_per_trade = 0.001    # 0.1% maximum loss per trade
max_daily_loss = 0.01         # 1% maximum daily loss
correlation_limit = 0.7       # Maximum correlation between positions

# Market Making Logic
enable_dynamic_spread = true  # Adjust spread based on volatility
enable_inventory_skew = true  # Skew prices based on inventory
enable_volume_scaling = true  # Scale orders based on volume

# Performance Tracking
track_spread_capture = true   # Track spread capture metrics
track_inventory_cost = true   # Track inventory holding costs
track_market_impact = true    # Track market impact costs

[hft_performance]
# HFT Performance Requirements

# Latency Targets
max_signal_latency = 1        # Maximum 1 microsecond for signal generation
max_order_latency = 10        # Maximum 10 microseconds for order placement
max_data_latency = 100        # Maximum 100 microseconds for data processing

# Throughput Requirements
max_trades_per_second = 10000 # Maximum 10,000 trades per second
max_orders_per_second = 50000 # Maximum 50,000 orders per second
max_data_updates_per_second = 100000 # Maximum 100,000 data updates per second

# Memory Requirements
max_memory_usage = 100        # Maximum 100 MB memory usage
max_allocation_size = 1024    # Maximum 1 KB per allocation
enable_memory_pool = true     # Use memory pools for allocations

# CPU Requirements
max_cpu_usage = 50            # Maximum 50% CPU usage
enable_cpu_affinity = true    # Pin to specific CPU cores
enable_hyperthreading = false # Disable hyperthreading for consistency

[hft_risk_management]
# HFT Risk Management Settings

# Position Limits
max_concurrent_positions = 10 # Maximum 10 concurrent positions
max_portfolio_risk = 0.01     # Maximum 1% portfolio risk
max_correlation_risk = 0.7    # Maximum 70% correlation between positions

# Loss Limits
max_drawdown = 0.05           # Maximum 5% drawdown
max_daily_loss = 0.02         # Maximum 2% daily loss
max_hourly_loss = 0.01        # Maximum 1% hourly loss

# Circuit Breakers
enable_circuit_breakers = true # Enable automatic circuit breakers
loss_threshold = 0.005        # 0.5% loss threshold for circuit breaker
recovery_time = 300           # 5 minutes recovery time

# Market Impact
max_market_impact = 0.001     # Maximum 0.1% market impact
enable_iceberg_orders = true  # Use iceberg orders for large positions
enable_twap_orders = true     # Use TWAP orders for execution

[hft_market_data]
# HFT Market Data Configuration

# Data Sources
primary_data_source = "binance_websocket"  # Primary data source
backup_data_source = "binance_rest"        # Backup data source
data_redundancy = 2                        # Number of redundant data feeds

# Data Quality
min_data_freshness = 100      # Maximum 100 microseconds data age
enable_data_validation = true # Validate data quality
enable_outlier_detection = true # Detect and filter outliers

# Order Book Depth
order_book_levels = 10        # Number of order book levels to track
enable_order_book_reconstruction = true # Reconstruct order book from trades
enable_imbalance_detection = true # Detect order book imbalances

# Market Microstructure
enable_tick_analysis = true   # Analyze individual ticks
enable_volume_profile = true  # Track volume profiles
enable_liquidity_analysis = true # Analyze liquidity patterns

[hft_execution]
# HFT Execution Configuration

# Order Types
enable_market_orders = true   # Enable market orders for immediate execution
enable_limit_orders = true    # Enable limit orders for price improvement
enable_stop_orders = true     # Enable stop orders for risk management

# Order Management
max_order_age = 1000          # Maximum 1 second order age
enable_order_cancellation = true # Enable automatic order cancellation
enable_order_modification = true # Enable order modification

# Smart Order Routing
enable_smart_routing = true   # Route orders to best venue
enable_latency_arbitrage = false # Disable latency arbitrage
enable_spread_capture = true  # Enable spread capture strategies

# Execution Algorithms
enable_twap = true            # Enable TWAP execution
enable_vwap = true            # Enable VWAP execution
enable_iceberg = true         # Enable iceberg orders
enable_participation = true   # Enable participation algorithms

[hft_monitoring]
# HFT Monitoring and Alerting

# Performance Metrics
track_latency = true          # Track execution latency
track_slippage = true         # Track price slippage
track_fill_rate = true        # Track order fill rates
track_profit_loss = true      # Track P&L metrics

# Alerting
enable_latency_alerts = true  # Alert on high latency
enable_loss_alerts = true     # Alert on losses
enable_risk_alerts = true     # Alert on risk violations
enable_system_alerts = true   # Alert on system issues

# Logging
log_level = "info"            # Logging level
enable_trade_logging = true   # Log all trades
enable_order_logging = true   # Log all orders
enable_performance_logging = true # Log performance metrics

# Reporting
enable_real_time_reporting = true # Real-time performance reporting
enable_daily_reports = true   # Daily performance reports
enable_risk_reports = true    # Risk management reports 