# Kalman Filter Strategy Configuration
# Optimized for profitability using momentum-based approach

# Core parameters
scale = 1.2
confidence_threshold = 0.2
deviation_threshold = 0.0005

# Signal filtering - Made more aggressive for trade generation
signal_threshold = 0.01 