# Kalman Filter Strategy Configuration
# Optimized for profitability using momentum-based approach

# Core parameters
scale = 1.2
confidence_threshold = 0.2
deviation_threshold = 0.0005

# Signal filtering - Made more aggressive for trade generation
signal_threshold = 0.01

# Kalman Filter Parameters
process_noise = 0.001         # Process noise covariance
measurement_noise = 0.01      # Measurement noise covariance
initial_uncertainty = 1.0     # Initial state uncertainty

# Risk Management
stop_loss_pct = 0.02          # 2% stop loss
take_profit_pct = 0.04        # 4% take profit
max_position_size = 0.1       # Maximum 10% of portfolio per trade 