# Market Maker Strategy Configuration
# Best for: Spread capture, order book analysis, inventory management

# Signal Generation
signal_threshold = 0.01     # 1% confidence threshold for maximum signals

# Order Book Simulation (for backtesting)
bid_price_offset = 0.9999       # Bid price offset from trade price
ask_price_offset = 1.0001       # Ask price offset from trade price
order_book_size_multiplier = 10.0 # Multiplier for simulated order book size

# Volatility Calculation
volatility_alpha = 0.1           # Alpha for exponential volatility calculation

# Volume Profile
volume_profile_alpha = 0.9       # Alpha for volume profile calculation
volume_profile_beta = 0.1        # Beta for volume profile calculation

# Momentum Parameters
momentum_threshold = 0.00005     # Very low momentum threshold for maximum signals
