# Mean Reversion Strategy Configuration
# Best for: Range-bound markets, mean reversion opportunities

# Core Parameters
window_size = 15              # Shorter window size for faster signals
max_trade_window = 8          # Shorter trade holding period
scale = 1.2                  # Higher signal scaling factor

# Mean Reversion Logic
deviation_threshold = 0.015   # Lower deviation threshold for more signals
reversion_strength = 0.6      # Higher expected reversion strength
signal_threshold = 0.3        # Lower confidence threshold for more signals

# Risk Management
stop_loss_pct = 0.02          # 2% stop loss
take_profit_pct = 0.04        # 4% take profit
max_position_size = 0.1       # Maximum 10% of portfolio per trade 