# Mean Reversion Strategy Configuration
# Best for: Range-bound markets, mean reversion opportunities

# Core Parameters
window_size = 8               # Very short window for ultra-fast signals
max_trade_window = 4          # Very short trade holding period
scale = 2.0                   # Very high scaling factor for strong signals
signal_threshold = 0.1        # Very low threshold for maximum signals

# Mean Reversion Logic
deviation_threshold = 0.005   # Very low deviation threshold for more signals
reversion_strength = 1.0      # Very high strength for strong signals

# Momentum Parameters
momentum_threshold = 0.00005  # Very low momentum threshold for more signals

# Risk Management
stop_loss_pct = 0.02          # 2% stop loss
take_profit_pct = 0.04        # 4% take profit
max_position_size = 0.1       # Maximum 10% of portfolio per trade 