[general]
strategy_name = "MeanReversionHftStrategy_Optimized"

[mean_reversion]
# Window for calculating moving average (reduced for faster response)
mean_window = 15
# Price deviation threshold from mean (increased for better signals)
deviation_threshold = 0.002
# Strength of mean reversion signal (increased for stronger signals)
reversion_strength = 3.0
# Maximum deviation before extreme signal (increased for better range)
max_deviation = 0.015

[volatility]
# Window for volatility calculation (reduced for faster response)
volatility_window = 8
# Minimum volatility for trading (increased for better opportunities)
volatility_threshold = 0.015
# Whether to adapt thresholds to market
adaptive_threshold = true

[volume]
# Window for volume analysis (reduced for faster response)
volume_window = 3
# Minimum volume increase (increased for stronger signals)
volume_threshold = 1.5
# Whether to require volume confirmation
volume_confirmation = true

[signals]
# Minimum confidence for trade (increased for better quality)
min_confidence = 0.25
# Maximum time to hold position in seconds (increased for better profits)
max_position_time = 30.0
# Profit target percentage (increased for better returns)
profit_target = 0.08
# Stop loss percentage (increased for better risk management)
stop_loss = 0.025
# Maximum trades per hour (reduced for quality over quantity)
max_trades_per_hour = 60
