# Mean Reversion Strategy Configuration
# Best for: Range-bound markets, mean reversion opportunities

# Core Parameters
window_size = 20              # Moving average window size
max_trade_window = 10         # Maximum trade holding period
scale = 1.0                  # Signal scaling factor

# Mean Reversion Logic
deviation_threshold = 0.02    # 2% deviation from mean
reversion_strength = 0.5      # Expected reversion strength
signal_threshold = 0.6        # 60% confidence threshold

# Risk Management
stop_loss_pct = 0.02          # 2% stop loss
take_profit_pct = 0.04        # 4% take profit
max_position_size = 0.1       # Maximum 10% of portfolio per trade 