# Momentum Scalping Strategy Configuration
# Best for: Short-term momentum, scalping opportunities

# Core Parameters
trade_window_size = 2         # Very short trade window for immediate signals
price_change_threshold = 0.000001  # Extremely low price change threshold
scale = 1.5                  # Higher signal scaling factor

# Scalping Logic
momentum_threshold = 0.0001   # Very low momentum threshold for maximum signals
volume_threshold = 0.9        # Below average volume threshold for more signals
signal_threshold = 0.1        # Extremely low confidence threshold for maximum signals

# Volume Analysis
volume_alpha = 0.8            # More responsive volume EMA
volume_beta = 0.2             # Higher weight for new volume data

# Risk Management
stop_loss_pct = 0.01          # 1% stop loss (tight for scalping)
take_profit_pct = 0.02        # 2% take profit
max_position_size = 0.05      # Maximum 5% of portfolio per trade 