[general]
strategy_name = "MomentumBreakoutHftStrategy"

[momentum]
# Short-term momentum window for quick signals
short_period = 3
# Long-term momentum window for trend confirmation
long_period = 10
# Minimum momentum percentage for signal generation (ultra-low for stable markets)
momentum_threshold = 0.005
# Rate of momentum change threshold for acceleration signals (ultra-low)
acceleration_threshold = 0.002

[volatility]
# Window size for volatility calculation
volatility_window = 5
# Minimum volatility percentage for trading (ultra-low for stable markets)
volatility_threshold = 0.05
# Multiplier for breakout detection bands
breakout_multiplier = 1.1

[volume]
# Window size for volume analysis
volume_window = 5
# Minimum volume increase percentage (ultra-low)
volume_threshold = 2.0
# Volume momentum threshold for confirmation (ultra-low)
volume_momentum = 1.0

[signals]
# Minimum confidence level for trade execution (ultra-low for testing)
min_confidence = 0.2
# Maximum time to hold position in seconds (very short for HFT)
max_position_time = 30.0
# Profit target percentage for take profit (ultra-low for stable markets)
profit_target = 0.1
# Stop loss percentage for risk management (ultra-tight for HFT)
stop_loss = 0.05
