# Neural Market Microstructure Strategy Configuration
# Optimized for profitability using momentum-based approach

# Core parameters
short_window = 5
medium_window = 20
long_window = 100
micro_window = 10

# Signal filtering - Made more aggressive for trade generation
signal_threshold = 0.01 