# Order Book Imbalance Strategy Configuration
# Optimized for profitability using momentum-based approach

# Core parameters
period = 10
buy_threshold = 0.1
sell_threshold = -0.1
scale = 2.0

# Signal filtering - Made more aggressive for trade generation
signal_threshold = 0.01
momentum_threshold = 0.00001 