# Order Book Imbalance Strategy Configuration
# Best for: Order book analysis and imbalance detection
# OPTIMIZED FOR MAXIMUM PROFIT

# Core Parameters
period = 5                    # Shorter period for more signals
scale = 3.0                   # Higher scaling factor for stronger signals
signal_threshold = 0.01       # Lower threshold for more signals

# Momentum Parameters
momentum_threshold = 0.00001  # Lower momentum threshold for more signals 