[general]
strategy_name = "Pulsar-MemOnly"
enabled = true
base_size = 1.5
max_position = 10.0
max_drawdown = 0.05

[memory]
reservoir_size = 128
snapshot_buffer_size = 12000
trade_buffer_size = 30000
book_events_buffer_size = 100000
knn_memory_size = 6000

[esn]
spectral_radius = 0.96
leak_rate = 0.25
connectivity = 0.18
input_scale = 0.25

[rls]
forgetting_factor = 0.992
regularization = 100.0
update_rate = 0.02

[knn]
neighbors = 24
distance_threshold = 0.05
min_memory_size = 40

[mpc]
decision_interval_ms = 1
execution_threshold = 0.000005
bootstrap_samples = 12
candidate_offsets = [0.25, 0.5, 1.0, 2.0]
candidate_sizes = [0.5, 1.0, 1.5, 2.0]
risk_penalty = 0.008
inventory_penalty = 0.008

[signals]
# require some recent activity to participate
min_event_intensity = 0.0
# take-profit and stop-loss bands (as return fraction)
tp_bps = 0.001
sl_bps = 0.00015
# require aggression alignment with score
aggression_align = false
aggr_min_abs = 0.0
require_dual_momentum = false
mode = "momentum"
min_score_mult = 0.05
vol_k = 0.0
vol_window = 12
r2_w = 0.6
r5_w = 0.3
aggr_w = 0.1
ei_w = 0.0
conf_gain = 5.0

[features]
normalization_window = 240
feature_count = 20
depth_levels = 5

[labels]
horizon_ms = 400
max_pending_labels = 600

[safety]
max_order_churn_per_sec = 12
cold_start_duration_ms = 800
confidence_threshold = 0.008
