# Fractal-Based HFT Strategy Configuration
# Best for: Geometric pattern recognition and market structure analysis
# OPTIMIZED FOR PROFITABILITY - FRACTAL ANALYSIS

# Fractal Analysis Parameters
fractal_period = 5
price_window_capacity = 200
volume_window_capacity = 200

# Pattern Recognition Thresholds
pattern_threshold = 0.3
trend_strength_threshold = 0.2
fractal_strength_threshold = 0.1

# Position Sizing Parameters
trading_size_min = 10.0
trading_size_max = 50.0

# Risk Management Thresholds
max_consecutive_losses = 3
min_win_rate_threshold = 0.4
stop_loss_percentage = 0.02
take_profit_percentage = 0.04

# Fractal Detection Settings
min_fractal_strength = 0.001
max_fractal_age = 100
fractal_confirmation_period = 3

# Support/Resistance Levels
level_tolerance = 0.001
min_level_touches = 2
level_strength_decay = 0.95

# Market Structure Analysis
fractal_dimension_window = 50
structure_analysis_enabled = true
breakout_detection_enabled = true

# Performance Tracking
performance_window = 50
adaptive_thresholds = true
dynamic_risk_management = true 