# Advanced Machine Learning HFT Strategy Configuration
# Best for: Ensemble ML models with pattern recognition and trend prediction
# OPTIMIZED FOR PROFITABILITY - MACHINE LEARNING

# Feature Engineering Parameters
feature_window = 50
price_window_capacity = 100
volume_window_capacity = 100

# Machine Learning Model Parameters
ensemble_weights = [0.3, 0.25, 0.25, 0.2]  # RF, NN, SVM, GB
gb_learning_rate = 0.1

# Signal Detection Thresholds
long_entry_threshold = 0.1
short_entry_threshold = -0.1
long_exit_threshold = -0.05
short_exit_threshold = 0.05

# Position Sizing Parameters
trading_size_min = 10.0
trading_size_max = 50.0

# Risk Management Thresholds
max_consecutive_losses = 3
min_win_rate_threshold = 0.4
max_volatility_threshold = 0.9
min_pattern_threshold = 0.2

# Neural Network Settings
nn_layers = [20, 10, 5, 1]
nn_learning_rate = 0.01
nn_momentum = 0.9

# Random Forest Settings
rf_n_trees = 10
rf_max_depth = 5
rf_min_samples_split = 2

# Support Vector Machine Settings
svm_kernel = "rbf"
svm_gamma = 0.1
svm_c = 1.0

# Gradient Boosting Settings
gb_n_estimators = 100
gb_max_depth = 3
gb_subsample = 0.8

# Model Performance Tracking
model_accuracy_window = 100
feature_importance_update_rate = 0.1
ensemble_weight_update_rate = 0.05

# Advanced ML Settings
adaptive_training = true
feature_selection = true
model_ensemble_voting = true
cross_validation_enabled = true 