# Deep Statistics & ML-Based HFT Strategy Configuration

# Feature Engineering Parameters
feature_dimension = 50
price_window_capacity = 1000
volume_window_capacity = 1000
timestamp_window_capacity = 1000
feature_window_capacity = 100

# ML Model Parameters
learning_rate = 0.001
momentum = 0.9
batch_size = 32
epochs = 100
validation_split = 0.2

# Prediction Parameters - OPTIMIZED FOR MORE TRADES
prediction_horizon = 3
confidence_threshold = 0.1
prediction_window = 50
accuracy_threshold = 0.4

# Statistical Analysis Parameters
rolling_window_size = 20
autocorrelation_lags = 20
volatility_regime_thresholds = [0.5, 1.5, 3.0]
regime_confidence_threshold = 0.7

# Technical Indicators
rsi_period = 14
macd_fast = 12
macd_slow = 26
macd_signal = 9
bollinger_period = 20
bollinger_std = 2.0

# Risk Management - MORE AGGRESSIVE
max_position_size = 1000.0
position_size_multiplier = 1.5
stop_loss_threshold = 0.015
take_profit_threshold = 0.02
max_consecutive_losses = 3
min_win_rate_threshold = 0.3

# Ensemble Model Weights
ml_model_weight = 0.25
statistical_model_weight = 0.25
microstructure_model_weight = 0.25
time_series_model_weight = 0.25

# Performance Tracking
track_prediction_accuracy = true
track_model_performance = true
track_feature_importance = true
adaptive_learning = true

# Market Microstructure
bid_ask_spread = 0.0001
order_flow_window = 100
volume_profile_levels = 10
price_impact_factor = 0.0001
market_depth_levels = 10

# Time Series Analysis
ar_order = 5
ma_order = 5
seasonal_period = 24
trend_smoothing = 0.1
residual_analysis = true

# Advanced Features
use_momentum_features = true
use_volatility_features = true
use_volume_features = true
use_temporal_features = true
use_statistical_features = true

# Model Training
online_learning = true
retrain_frequency = 1000
feature_selection = true
cross_validation = false
early_stopping = true

# Prediction Confidence - MORE AGGRESSIVE
min_confidence_for_trade = 0.1
confidence_decay_rate = 0.9
ensemble_voting = true
model_uncertainty = true

# Market Regime Detection
regime_detection_enabled = true
regime_transition_threshold = 0.1
regime_persistence = 0.9
adaptive_position_sizing = true

# Performance Optimization
prediction_cache_size = 100
feature_cache_size = 50
model_update_frequency = 10
memory_efficient = true 