# Profitable Mean Reversion Strategy Configuration
# Best for: Mean reversion trading with high win rates
# OPTIMIZED FOR PROFITABILITY - CONSERVATIVE SETTINGS

# Data Window Parameters - OPTIMIZED FOR MEAN REVERSION
bb_window = 20
rsi_window = 14
atr_window = 14

# Risk Management Parameters
volatility_score = 0.5
position_size_multiplier = 1.0

# Data Window Capacities
price_window_capacity = 100
volume_window_capacity = 100

# Bollinger Bands Parameters
bb_std_dev_multiplier = 2.0

# RSI Parameters - OPTIMIZED FOR MEAN REVERSION
rsi_oversold_threshold = 35.0           # More aggressive oversold
rsi_overbought_threshold = 65.0         # More aggressive overbought

# Position Sizing Parameters
trading_size_min = 10.0
trading_size_max = 50.0

# Risk Management Thresholds
stop_loss_atr_multiplier = 2.0          # Stop loss at 2x ATR
take_profit_atr_multiplier = 3.0        # Take profit at 3x ATR
max_consecutive_losses = 3              # Conservative risk management
min_win_rate_threshold = 0.4            # Minimum win rate to continue trading

# Volume Analysis
volume_ratio_threshold = 1.5            # Minimum volume ratio for signals
volume_boost_factor = 1.2               # Volume boost for position sizing

# Signal Quality Parameters
min_bb_position = 0.05                  # More aggressive BB position for entry
max_bb_position = 0.95                  # More aggressive BB position for entry
rsi_confirmation_threshold = 0.7        # RSI confirmation strength
volume_confirmation_threshold = 0.6     # Volume confirmation strength

# Performance Tracking
performance_window = 50                 # Trades to track for performance
adaptive_position_sizing = true         # Enable adaptive position sizing
risk_adjusted_returns = true            # Enable risk-adjusted returns 