# Quantum HFT Strategy Configuration
# Best for: High-frequency trading with ensemble machine learning
# OPTIMIZED FOR MAXIMUM PROFIT - AGGRESSIVE SETTINGS

# Data Window Parameters - OPTIMIZED FOR FASTER SIGNAL GENERATION
short_window = 8
long_window = 16
rsi_window = 10
bb_window = 14
vwap_window = 30

# Ensemble Weights (initially equal, will adapt)
ensemble_weight_linear = 0.167
ensemble_weight_macd = 0.167
ensemble_weight_rsi = 0.167
ensemble_weight_bollinger = 0.167
ensemble_weight_vwap = 0.167
ensemble_weight_ensemble = 0.167

# Risk Management Parameters
liquidity_score = 0.5
momentum_score = 0.5

# Learning Parameters
learning_rate = 0.01

# Data Window Capacities
price_window_capacity = 1000
volume_window_capacity = 1000
macd_window_capacity = 100
rsi_window_capacity = 100
bb_window_capacity = 100
vwap_window_capacity = 100

# MACD Parameters
macd_signal_window = 9

# Bollinger Bands Parameters
bb_std_dev_multiplier = 2.0

# RSI Parameters
rsi_default_value = 50.0

# Signal Generation Thresholds - OPTIMIZED FOR MORE TRADES
trend_strength_threshold = 0.2          # Reduced from 0.4 for more trend signals
momentum_threshold = 0.3                # Reduced from 0.5 for more momentum signals
momentum_strong_threshold = 0.5         # Reduced from 0.7 for more strong momentum signals
rsi_oversold_threshold = 30.0           # Increased from 25.0 for more oversold signals
rsi_overbought_threshold = 70.0         # Decreased from 75.0 for more overbought signals
bb_breakout_threshold = 0.5             # Reduced from 0.7 for more breakout signals
ensemble_threshold = 0.3                # Reduced from 0.4 for more ensemble signals
ensemble_strong_threshold = 0.4         # Reduced from 0.6 for more strong ensemble signals
trend_strength_min = 0.05               # Reduced from 0.15 for more trend signals
trend_strength_min_trend = 0.05         # Reduced from 0.1 for more trend signals
confidence_min = 0.4                    # Reduced from 0.55 for more trades
confidence_quality_threshold = 0.4      # Reduced from 0.6 for more trades
contributing_models_min = 1             # Keep at 1 for maximum trades

# Confidence Boost Values - OPTIMIZED FOR HIGHER CONFIDENCE
trend_confidence_weight = 0.8           # Increased from 0.7
momentum_confidence_weight = 0.6        # Increased from 0.5
momentum_strong_confidence_weight = 0.7 # Increased from 0.6
rsi_confidence_boost = 0.5              # Increased from 0.4
rsi_confidence_strong = 0.6             # Increased from 0.5
bb_confidence_boost = 0.4               # Increased from 0.3
bb_confidence_strong = 0.5              # Increased from 0.4
ensemble_confidence_weight = 0.7        # Increased from 0.6
ensemble_confidence_strong = 0.8        # Increased from 0.7
position_rsi_confidence = 0.5           # Increased from 0.4
position_bb_confidence = 0.4            # Increased from 0.3
position_ensemble_confidence = 0.6      # Increased from 0.5

# Risk Filter Parameters - OPTIMIZED FOR LESS FILTERING
volatility_high_threshold = 0.99        # Increased from 0.98 for less filtering
volatility_low_threshold = 0.001        # Reduced from 0.005 for less filtering
volatility_high_reduction = 0.98        # Increased from 0.95 for less reduction
volatility_low_reduction = 0.99         # Increased from 0.98 for less reduction
liquidity_low_threshold = 0.0001        # Reduced from 0.001 for less filtering
liquidity_high_threshold = 50.0         # Increased from 20.0 for less filtering
liquidity_low_reduction = 0.98          # Increased from 0.95 for less reduction
liquidity_high_boost = 1.3              # Increased from 1.2 for more boost
momentum_high_threshold = 0.95          # Increased from 0.9 for less filtering
momentum_boost = 1.3                    # Increased from 1.2 for more boost
momentum_reduction = 0.99               # Increased from 0.98 for less reduction
filter_significant_threshold = 0.90     # Reduced from 0.95 for more logging

# Risk Score Update Parameters - OPTIMIZED FOR FASTER RESPONSE
volatility_window_size = 10
liquidity_window_size = 10
momentum_window_size = 5
volatility_multiplier = 100.0
liquidity_max_ratio = 2.0

# Position Management
position_ensemble_sell_threshold = -0.3 # Reduced from -0.5 for more sell signals 