# RSI Strategy Configuration
# Best for: Mean reversion, overbought/oversold conditions
# OPTIMIZED FOR REDUCED DRAWDOWN AND BETTER RISK MANAGEMENT

# Core Parameters
period = 14                   # Standard RSI period for more reliable signals
overbought = 70.0             # Standard overbought threshold
oversold = 30.0               # Standard oversold threshold
scale = 2.0                   # Reduced scaling factor for lower risk
signal_threshold = 0.3        # Higher threshold for more reliable signals

# Momentum Parameters
momentum_threshold = 0.0001   # Higher momentum threshold for more reliable signals 