# RSI Strategy Configuration
# Best for: Mean reversion, overbought/oversold conditions
# ULTRA-OPTIMIZED FOR MAXIMUM PROFIT

# Core Parameters
period = 4                    # Shorter period for more signals
overbought = 68.0             # Lower overbought threshold for more signals
oversold = 32.0               # Higher oversold threshold for more signals
scale = 3.5                   # Higher scaling factor for stronger signals
signal_threshold = 0.1        # Lower threshold for more signals

# Momentum Parameters
momentum_threshold = 0.00003  # Lower momentum threshold for more signals 