# RSI Strategy Configuration
# Best for: Mean reversion, overbought/oversold conditions

# Core Parameters
period = 5                    # Very short period for ultra-fast signals
overbought = 70.0             # Standard overbought threshold
oversold = 30.0               # Standard oversold threshold
scale = 2.0                   # Very high scaling factor for strong signals
signal_threshold = 0.1        # Very low threshold for maximum signals

# Momentum Parameters
momentum_threshold = 0.0001   # Very low momentum threshold for more signals 