# Sentiment Analysis Strategy Configuration

[sentiment_weights]
social_sentiment_weight = 0.25
news_sentiment_weight = 0.3
volume_sentiment_weight = 0.25
price_sentiment_weight = 0.2

[sentiment_thresholds]
buy_threshold = 0.25
sell_threshold = -0.25
strong_buy_threshold = 0.5
strong_sell_threshold = -0.5

[windows]
short_window = 10
medium_window = 30
long_window = 60
sentiment_history_window = 100

[feature_extraction]
price_window = 20
volume_window = 10
volatility_window = 20
trend_window = 20

[confidence_calculation]
min_confidence = 0.3
confidence_decay_factor = 0.95
sentiment_agreement_threshold = 0.5

[risk_management]
max_position_size = 30.0
max_drawdown = 0.03
stop_loss = 0.012
take_profit = 0.025
max_consecutive_losses = 2

[performance_tracking]
track_sentiment_sources = true
track_confidence_levels = true
track_sentiment_trends = true
