# Spline Strategy Configuration
# Optimized for profitability using momentum-based approach

# Core parameters
window_size = 10
derivative_buy_threshold = 0.001
derivative_sell_threshold = -0.001
scale = 2.0

# Signal filtering
signal_threshold = 0.1
momentum_threshold = 0.00005 