# Spline Strategy Configuration
# Optimized for profitability using momentum-based approach

# Core parameters
window_size = 10
derivative_buy_threshold = 0.001
derivative_sell_threshold = -0.001
scale = 2.0

# Signal filtering - Made more aggressive for trade generation
signal_threshold = 0.01
momentum_threshold = 0.00001 