[general]
strategy_name = "StochasticHftStrategy"

[stochastic]
# Very short period for ultra-fast signals
k_period = 3
buffer_capacity = 1000

[signals]
# Very low confidence threshold for maximum trading opportunities
min = 0.5
