[general]
strategy_name = "StochasticHftStrategy"

[stochastic]
# Conservative Stochastic settings for high-quality signals
k_period = 21
d_period = 7
oversold = 15.0
overbought = 85.0
# Increased buffer capacity for more stable calculations
buffer_capacity = 2000

[signals]
# High confidence thresholds for quality signals
min = 0.7
# High confidence weights for reliable signals
oversold = 0.9
overbought = 0.9
crossover = 0.85

[risk]
max_consecutive_losses = 2
signal_cooldown_ms = 100
