[general]
strategy_name = "StochasticHftStrategy"

[stochastic]
# Stochastic settings for historical data
k_period = 14
buffer_capacity = 1000

[signals]
# Confidence threshold for quality signals
min = 0.8

[risk]
max_consecutive_losses = 3
signal_cooldown_ms = 1000
