[general]
strategy_name = "StochasticHftStrategy"

[stochastic]
# Very conservative Stochastic settings for maximum signal quality
k_period = 50
d_period = 15
oversold = 25.0
overbought = 75.0
# Increased buffer capacity for more stable calculations
buffer_capacity = 2000

[signals]
# Maximum confidence thresholds for best signal quality
min = 0.90
# Maximum confidence weights for most reliable signals
oversold = 0.98
overbought = 0.98
crossover = 0.95

[risk]
max_consecutive_losses = 3
signal_cooldown_ms = 1000
