# HFT Trading Configuration
# Realistic parameters for live trading

[exchange]
# Binance fees (taker/maker)
taker_fee = 0.001  # 0.1% taker fee
maker_fee = 0.0001  # 0.01% maker fee (with rebate)
maker_rebate = 0.0001  # 0.01% rebate for maker orders

# Slippage simulation
min_slippage = 0.00001  # 1 tick minimum slippage
max_slippage = 0.0001   # 10 ticks maximum slippage
slippage_volatility = 0.5  # How much slippage varies with volatility

[risk_management]
# Position sizing
max_position_size = 500.0   # Reduced maximum position size for lower risk
max_daily_loss = 500.0      # Reduced maximum daily loss
max_drawdown = 0.15         # 15% maximum drawdown (much more conservative)

# Signal filtering
min_signal_strength = 0.4   # Higher signal strength requirement for better quality
min_edge_over_cost = 1.5    # Higher edge requirement for more profitable trades

# Circuit breakers
max_consecutive_losses = 3   # Stop trading after 3 consecutive losses (more conservative)
cooldown_period = 600        # Wait 10 minutes after circuit breaker

[order_management]
# Order types and timing
use_limit_orders = true      # Use limit orders instead of market orders
limit_order_timeout = 1.0    # Cancel limit orders after 1 second
min_spread_capture = 0.00005 # Only place orders if spread > 0.5 ticks

# Queue position simulation
queue_position_penalty = 0.00002  # Additional cost for being deep in queue
partial_fill_probability = 0.3    # 30% chance of partial fills

[performance_tracking]
# Metrics to track
track_fill_rate = true
track_slippage = true
track_fees = true
track_rebates = true
track_queue_position = true 