# Trading Configuration
# This file contains the complete trading configuration used by the trading bot

[position_sizing]
trading_size_min = 15.0
trading_size_max = 35.0
trading_symbol = "DOGEUSDT"

[exchange]
taker_fee = 0.00005
maker_fee = 0.00005
maker_rebate = 0.000025
tick_size = 0.00001
min_notional = 10.0
max_order_size = 1000000.0
step_size = 0.5

[slippage]
min_slippage = 0.00001
max_slippage = 0.001
volatility_multiplier = 1.5
size_multiplier = 1.2
market_order_volatility = 0.002
taker_order_volatility = 0.001

[risk_management]
max_position_size = 1000000.0
max_daily_loss = 1000.0
max_drawdown = 0.08
max_leverage = 1.0
min_signal_strength = 0.6
max_consecutive_losses = 4
cooldown_period = 3
max_trades_per_hour = 300
initial_margin = 0.1
maintenance_margin = 0.05

[order_execution]
order_timeout = 5.0
max_retries = 3
retry_delay = 0.1

[market_data]
min_trade_size = 1.0
max_price_change = 0.1
outlier_threshold = 3.0
trading_hours_start = 0
trading_hours_end = 24

[performance_tracking]
track_fill_rate = false
track_slippage = true
track_fees = true
track_rebates = true
track_order_rejections = false
calculate_sharpe_ratio = false
calculate_sortino_ratio = false
calculate_max_drawdown = true
calculate_calmar_ratio = false
calculate_profit_factor = false

[backtest_settings]
initial_capital = 10000.0
commission_model = "binance"
slippage_model = "realistic"
fill_model = "immediate"
handle_data_gaps = true
interpolate_missing_data = false
filter_outliers = true
prevent_lookahead_bias = true
use_point_in_time_data = true
simulate_market_microstructure = false
account_for_latency_in_signals = false
simulate_order_queue_position = false
simulate_partial_fills = false
simulate_order_cancellations = false
simulate_market_impact = false
market_impact_model = "none"
impact_decay_rate = 0.0
simulate_order_delays = false
simulate_exchange_errors = false
simulate_network_timeouts = false
limit_order_fill_rate = 0.95
partial_fill_probability = 0.1
partial_fill_ratio = 0.5
invalid_order_probability = 0.001
rejection_reasons = [
    "insufficient_balance",
    "invalid_price",
    "invalid_quantity",
]
handle_market_halts = false
halt_probability = 0.0001
halt_duration_min = 60
halt_duration_max = 300
base_spread = 0.0001
spread_volatility = 0.00005
spread_widening_factor = 1.5
order_book_depth = 10
market_impact_factor = 0.0001
track_queue_position = false
track_latency = false
track_market_impact = false
total_latency_model = "realistic"
propagation_delay = 0.01
transmission_delay = 0.002
queuing_delay = 0.005
processing_delay = 0.003
latency_spike_probability = 0.01
latency_spike_multiplier = 5.0
congestion_latency_factor = 1.2
exchange_processing_time = 0.001
order_matching_latency = 0.0005
market_data_latency = 0.001
signal_generation_time = 0.0001
order_construction_time = 0.0001
risk_check_time = 0.0001
order_book_simulation = false
bid_ask_spread_model = "none"
spread_volatility_factor = 0.0
spread_widening_events = false
order_book_levels = 1
level_size_distribution = "none"
min_level_size = 0.0
max_level_size = 0.0
market_maker_presence = false
mm_spread_tightening = 0.0
mm_inventory_management = false
mm_risk_aversion = 0.0
hft_competition = false
hft_latency_advantage = 0.0
hft_order_cancellation_rate = 0.0
hft_market_impact = 0.0
disable_drawdown_limit = false
