# Trading Configuration
# This file contains both general trading settings and backtest-specific settings
# 
# GENERAL TRADING SETTINGS (used by both trade and backtest commands):
# - [exchange] - Exchange fees and market structure
# - [slippage] - Slippage modeling
# - [order_execution] - Order execution parameters
# - [risk_management] - Risk management rules
# - [market_data] - Market data handling
# - [performance_tracking] - Performance metrics
# - [position_sizing] - Dynamic position sizing per pair
#
# BACKTEST-SPECIFIC SETTINGS (only used by backtest command):
# - [backtest_settings] - Backtest-only parameters (ignored by trade command)

[exchange]
# Binance fees (realistic for 2024)
taker_fee = 0.001      # 0.1% taker fee
maker_fee = 0.0001     # 0.01% maker fee
maker_rebate = 0.0001  # 0.01% rebate for maker orders
tick_size = 0.00001    # Minimum price increment (1 tick)
min_notional = 1.0     # Minimum order value in USDT
max_order_size = 1000.0 # Maximum order size in base currency

# DOGEUSDT specific lot size requirements
step_size = 1.0        # Quantity step size (1 DOGE increments)

[slippage]
min_slippage = 0.00001
max_slippage = 0.0005
volatility_multiplier = 2.0
size_multiplier = 1.5
market_order_volatility = 0.1  # Volatility assumption for market orders
taker_order_volatility = 0.2   # Volatility assumption for taker orders

[order_execution]
order_timeout = 30.0
max_retries = 3
retry_delay = 1.0

[risk_management]
max_position_size = 1000.0
max_daily_loss = 1000.0
max_drawdown = 0.20
max_leverage = 1.0
min_signal_strength = 0.3     # Minimum signal strength to trade
max_consecutive_losses = 5
cooldown_period = 300
max_trades_per_hour = 100
initial_margin = 1.0
maintenance_margin = 0.8



[market_data]
min_trade_size = 0.1
max_price_change = 0.1
outlier_threshold = 3.0
trading_hours_start = 0
trading_hours_end = 24

[performance_tracking]
track_fill_rate = true
track_slippage = true
track_fees = true
track_rebates = true
track_order_rejections = true
calculate_sharpe_ratio = true
calculate_sortino_ratio = true
calculate_max_drawdown = true
calculate_calmar_ratio = true
calculate_profit_factor = true

[backtest_settings]
# BACKTEST-SPECIFIC SETTINGS (only used by backtest command)
# These settings are ignored by the trade command

# Simulation parameters
initial_capital = 10000.0
commission_model = "binance"
slippage_model = "realistic"
fill_model = "probabilistic"

# Data handling (backtest-specific)
handle_data_gaps = true
interpolate_missing_data = false
filter_outliers = true

# Bias prevention (backtest-specific)
prevent_lookahead_bias = true
use_point_in_time_data = true

# Simulation-only features (not used in live trading)
simulate_market_microstructure = true
account_for_latency_in_signals = true
simulate_order_queue_position = true
simulate_partial_fills = true
simulate_order_cancellations = true

# Market impact simulation (backtest-specific)
simulate_market_impact = true
market_impact_model = "linear"
impact_decay_rate = 0.1

# Realistic order execution simulation
simulate_order_delays = true
simulate_exchange_errors = true
simulate_network_timeouts = true

# Fill and rejection simulation (backtest-specific)
limit_order_fill_rate = 0.65
partial_fill_probability = 0.25
partial_fill_ratio = 0.6
invalid_order_probability = 0.02
rejection_reasons = ["insufficient_balance", "invalid_price", "order_too_small"]

# Market events simulation (backtest-specific)
handle_market_halts = true
halt_probability = 0.001
halt_duration_min = 60
halt_duration_max = 3600

# Spread and market impact simulation (backtest-specific)
base_spread = 0.00002
spread_volatility = 0.3
spread_widening_factor = 2.0
order_book_depth = 10
market_impact_factor = 0.0001

# Performance tracking simulation (backtest-specific)
track_queue_position = true
track_latency = true
track_market_impact = true

# Latency simulation (backtest-specific)
total_latency_model = "realistic"
propagation_delay = 0.010
transmission_delay = 0.002
queuing_delay = 0.005
processing_delay = 0.003
latency_spike_probability = 0.01
latency_spike_multiplier = 5.0
congestion_latency_factor = 2.0
exchange_processing_time = 0.001
order_matching_latency = 0.002
market_data_latency = 0.001
signal_generation_time = 0.001
order_construction_time = 0.001
risk_check_time = 0.002

# Market microstructure simulation (backtest-specific)
order_book_simulation = true
bid_ask_spread_model = "dynamic"
spread_volatility_factor = 0.3
spread_widening_events = true
order_book_levels = 10
level_size_distribution = "exponential"
min_level_size = 1.0
max_level_size = 1000.0
market_maker_presence = true
mm_spread_tightening = 0.8
mm_inventory_management = true
mm_risk_aversion = 0.5
hft_competition = true
hft_latency_advantage = 0.001
hft_order_cancellation_rate = 0.3
hft_market_impact = 0.0001 