# Trading Configuration
# This file contains the position sizing configuration used by the trading bot

[position_sizing]
trading_size_min = 10.0
trading_size_max = 50.0
default_trading_symbol = "DOGEUSDT" 