[general]
strategy_name = "TrendFollowingHftStrategy"

[trend]
# Short-term trend window
short_window = 8
# Long-term trend window
long_window = 20
# Minimum trend strength (ultra-low for testing)
trend_strength = 0.001
# Trend confirmation threshold
trend_confirmation = 0.002

[momentum]
# Window for momentum calculation
momentum_window = 10
# Momentum threshold for entry (ultra-low for testing)
momentum_threshold = 0.002
# Acceleration threshold
acceleration_threshold = 0.001
# Momentum decay factor
momentum_decay = 0.95

[confirmation]
# Whether to require volume confirmation
volume_confirmation = false
# Volume confirmation threshold
volume_threshold = 5.0
# Whether to require price confirmation
price_confirmation = true
# Window for confirmation
confirmation_window = 5

[signals]
# Minimum confidence for trade (ultra-low for testing)
min_confidence = 0.2
# Maximum time to hold position in seconds
max_position_time = 25.0
# Profit target percentage (ultra-low for testing)
profit_target = 0.04
# Stop loss percentage (tight for HFT)
stop_loss = 0.02
# Maximum trades per minute
max_trades_per_minute = 60
