[general]
strategy_name = "TrendFollowingHftStrategy_Optimized"

[trend]
# Short-term trend window (reduced for faster response)
short_window = 6
# Long-term trend window (reduced for faster response)
long_window = 15
# Minimum trend strength (increased for better signals)
trend_strength = 0.002
# Trend confirmation threshold (increased for better confirmation)
trend_confirmation = 0.003

[momentum]
# Window for momentum calculation (reduced for faster response)
momentum_window = 8
# Momentum threshold for entry (increased for better signals)
momentum_threshold = 0.003
# Acceleration threshold (increased for better signals)
acceleration_threshold = 0.002
# Momentum decay factor (reduced for longer momentum)
momentum_decay = 0.90

[confirmation]
# Whether to require volume confirmation
volume_confirmation = true
# Volume confirmation threshold (increased for stronger signals)
volume_threshold = 3.0
# Whether to require price confirmation
price_confirmation = true
# Window for confirmation (reduced for faster response)
confirmation_window = 3

[signals]
# Minimum confidence for trade (increased for better quality)
min_confidence = 0.35
# Maximum time to hold position in seconds (increased for better profits)
max_position_time = 35.0
# Profit target percentage (increased for better returns)
profit_target = 0.06
# Stop loss percentage (increased for better risk management)
stop_loss = 0.025
# Maximum trades per minute (reduced for quality over quantity)
max_trades_per_minute = 40
