# Ultra-Fast Strategy Configuration
# Best for: Ultra-low latency directional trading, momentum capture

# Core Parameters (optimized for speed)
buffer_size = 64           # Fixed buffer size for minimal allocations
fast_ema_alpha = 0.1       # Less responsive fast EMA (10-period equivalent)
slow_ema_alpha = 0.05      # Less responsive slow EMA (20-period equivalent)
volatility_window = 20     # Longer volatility calculation window

# Signal Thresholds (more conservative)
buy_threshold = 0.001      # Much higher buy threshold for stability
sell_threshold = -0.001    # Much higher sell threshold for stability
volume_threshold = 1.5     # Higher volume threshold for better signals
signal_threshold = 0.5     # Much higher confidence threshold for quality signals

# Momentum Parameters (more conservative)
momentum_threshold = 0.001 # Much higher momentum threshold for stronger signals

# Signal Generation Parameters
min_buffer_size = 5        # Slightly larger buffer for more stable signals
volatility_threshold = 0.005 # Higher volatility threshold for stability
volatility_factor_high = 0.8 # Reduce signals in high volatility
volatility_factor_low = 1.2  # Moderate boost in low volatility

# Signal Weights
price_momentum_weight = 0.5 # Balanced weight for price momentum
ema_signal_weight = 0.3     # Keep EMA crossover weight
volume_signal_weight = 0.2  # Increased volume confirmation weight

# Volume Analysis
volume_alpha = 0.7          # Less responsive volume EMA for stability
volume_beta = 0.3           # More weight for historical volume data
