# VWAP Deviation Strategy Configuration
# Optimized for profitability using momentum-based approach

# Core parameters
period = 10
deviation_threshold = 0.001

# Signal filtering - Optimized for maximum profitability
signal_threshold = 0.005
momentum_threshold = 0.000005 