# Z-Score Strategy Configuration
# Best for: Statistical arbitrage, mean reversion

# Core Parameters
period = 10                   # Very short period for ultra-fast signals
buy_threshold = -0.000005     # Lower buy threshold for more signals
sell_threshold = 0.000005     # Lower sell threshold for more signals
scale = 2.0                   # Very high scaling factor for strong signals
signal_threshold = 0.1        # Very low threshold for maximum signals

# Momentum Parameters
momentum_threshold = 0.00005  # Very low momentum threshold for more signals 