# Z-Score Strategy Configuration
# Best for: Statistical arbitrage, mean reversion
# CONSERVATIVE FOR BETTER WIN RATE

# Core Parameters
period = 8                    # Medium period for balanced signals
buy_threshold = -0.0005       # Higher buy threshold for better signals
sell_threshold = 0.0005       # Higher sell threshold for better signals
scale = 2.0                   # Moderate scaling factor
signal_threshold = 0.3        # Higher threshold for quality signals

# Momentum Parameters
momentum_threshold = 0.0001   # Higher momentum threshold for quality signals 