# Z-Score Strategy Configuration
# Best for: Statistical arbitrage, mean reversion

# Core Parameters
period = 30                   # Shorter period for faster signals
buy_threshold = -0.000005     # Lower buy threshold for more signals
sell_threshold = 0.000005     # Lower sell threshold for more signals
scale = 1.2                  # Higher signal scaling factor

# Z-Score Logic
zscore_threshold = 1.5        # Lower Z-score threshold for more signals
mean_reversion_strength = 0.6 # Higher expected mean reversion strength
signal_threshold = 0.3        # Lower confidence threshold for more signals

# Risk Management
stop_loss_pct = 0.02          # 2% stop loss
take_profit_pct = 0.04        # 4% take profit
max_position_size = 0.1       # Maximum 10% of portfolio per trade 