[package]
name = "binance-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
binance-exchange = { path = "../../exchanges/binance" }
env_logger = "0.10"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
log = "0.4.27"
strategies = { path = "../../strategies" }
