[package]
name = "binance-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
#core = { path = "../../core" }
#binance-exchange = { path = "../../exchanges/binance" }
#mean_reversion = { path = "../../strategies/mean_reversion" }
#tokio = "1.45.0"

binance-exchange = { path = "../../exchanges/binance" }
env_logger = "0.10"
tokio = { version = "1", features = ["full"] }
log = "0.4.27"